# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-07 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0008_auto_20190607_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='neighbourhood',
            new_name='artType',
        ),
        migrations.AlterField(
            model_name='authorities',
            name='neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='business',
            name='artType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='health',
            name='neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.neighbourhood'),
        ),
    ]
